# Numpy Arrays

In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]


In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
mylist

[1, 2, 3]

In [6]:
myarray = np.array(mylist)

In [7]:
myarray

array([1, 2, 3])

In [8]:
type(myarray)

numpy.ndarray

In [9]:
my_matrix =[[1,2,3],[4,5,6],[7,8,9]]

In [10]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.ones(2)

array([1., 1.])

In [20]:
np.ones((2,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [24]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [27]:
len(np.linspace(0,5,20))

20

In [28]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
np.random.rand(1)

array([0.61452318])

In [35]:
np.random.rand(5,2)

array([[0.41811997, 0.04551535],
       [0.87561942, 0.66392449],
       [0.68727428, 0.07329768],
       [0.17166054, 0.59969572],
       [0.93919128, 0.23864466]])

In [36]:
np.random.randn(1)

array([-0.66863582])

In [37]:
np.random.randn(2,3)

array([[ 0.34816848,  0.25898127, -0.64028625],
       [ 0.82882612, -0.51780456,  0.70721476]])

In [39]:
np.random.randint(-100,100,50)

array([ 50,  57, -10,  39,  18,  85, -53,   3,  62,  -3, -97,  35,  66,
       -40,  84,  78,   7, -92, -61, -24,  54, -81, -62, -60, -54,  89,
        11, -14, -61, -13,  84,  20,   3, -19,  86,  67,  71,   0, -53,
        92,  75,  59, -67, -85, -52,  -4,  12,  25,  76,  60])

In [41]:
np.random.randint(-100,100,(4,5))

array([[ 86, -96,  12,  15,  63],
       [-21,  27,  96,  58,  13],
       [-70,  -7, -96,  16,  64],
       [ 13,  42,   0,  60, -31]])

In [43]:
np.random.seed(46)
np.random.rand(4)

array([0.78383235, 0.63483371, 0.24904309, 0.75807586])

In [44]:
arr = np.arange(0,30)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [46]:
arr.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [51]:
renarr= np.random.randint(0,100,10)

In [52]:
renarr

array([98, 59, 79, 30, 98,  2, 22, 87, 72, 48])

In [53]:
renarr.min()

2

In [54]:
renarr.max()

98

In [55]:
renarr.argmax()

0

In [56]:
renarr.argmin()

5

In [57]:
renarr.dtype

dtype('int32')

In [58]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [59]:
arr.shape

(30,)

In [60]:
arr =arr.reshape(6,5)

In [61]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [62]:
arr.shape

(6, 5)

In [63]:
np.arange(0,101,10)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [64]:
myarray = np.array

In [65]:
myarray

<function numpy.array>

In [66]:
mylist =(0,101,10)

In [67]:
mylist

(0, 101, 10)

# Indexing and Selection

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[7]

7

In [5]:
arr[1:9]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
arr[:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [8]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr[0:5] = 100

In [10]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
arr=np.arange(0,11)

In [12]:
slice_of_arr = arr[0:5]

In [13]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [14]:
arr_copy = arr.copy()

In [15]:
arr_copy[:]=100

In [16]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [19]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [20]:
arr_2d.shape

(3, 3)

In [21]:
arr_2d[0,0]

5

In [22]:
arr_2d[2]

array([35, 40, 45])

In [23]:
arr_2d[2,2]

45

In [24]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [25]:
arr = np.arange(1,11)

In [26]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [28]:
bool_arr = arr>4

In [29]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [30]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [31]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [32]:
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

In [33]:
dice_rolls>2

array([ True, False,  True, False,  True, False, False,  True, False,
        True, False, False,  True,  True,  True,  True,  True, False,
        True, False,  True,  True,  True,  True, False,  True,  True,
        True,  True])

In [34]:
total_rolls_over_two = dice_rolls>2

In [35]:
total_rolls_over_two

array([ True, False,  True, False,  True, False, False,  True, False,
        True, False, False,  True,  True,  True,  True,  True, False,
        True, False,  True,  True,  True,  True, False,  True,  True,
        True,  True])

In [36]:
dice_rolls[total_rolls_over_two]

array([3, 5, 5, 5, 4, 4, 5, 3, 4, 5, 4, 6, 6, 3, 6, 3, 5, 6, 5])

In [38]:
len(dice_rolls[dice_rolls>2])

19

# Numpy Operations

In [39]:
arr = np.arange(0,11)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr +5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [42]:
arr -5

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [43]:
arr * arr 

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [44]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
arr /2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [47]:
arr/arr

C:\Users\KIIT\AppData\Local\Temp\ipykernel_312\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [48]:
1 /arr

C:\Users\KIIT\AppData\Local\Temp\ipykernel_312\4127448963.py:1: RuntimeWarning: divide by zero encountered in divide
  1 /arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [49]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [50]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [51]:
np.log(arr)

C:\Users\KIIT\AppData\Local\Temp\ipykernel_312\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [52]:
arr.sum()

55

In [53]:
arr.mean()

5.0

In [54]:
arr.var()

10.0

In [55]:
arr.std()

3.1622776601683795

In [56]:
arr2d= np.arange(0,25).reshape(5,5)

In [57]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [58]:
arr2d.sum()

300

In [59]:
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])